branch-defaults:
  master:
    environment: IdeaLyst-dev2
    group_suffix: null
  test:
    environment: IdeaLyst-dev2
environment-defaults:
  IdeaLyst-dev2:
    branch: null
    repository: null
global:
  application_name: IdeaLyst
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
